development:
  adapter: redis
  timeout: 1
  url: <%= ENV["REDIS_URL"] || "redis://localhost:6379/1"  %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] || "redis://localhost:6379/1"  %>
  timeout: 1
  channel_prefix: homeland_prod
