# View the cron expression detail at https://crontab.cronhub.io/
doorkeeper_cleanup:
  cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
  class: "Scheduler::DoorkeeperCleanupJob"
  queue: cleanup
  description: "Cleanup expired OAuth tokens"

notification_cleanup:
  cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
  class: "Scheduler::NotificationCleanupJob"
  queue: cleanup
  description: "Cleanup expired notifications"

spam_cleanup:
  cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
  class: "Scheduler::SpamCleanupJob"
  queue: cleanup
  description: "Cleanup spam contents before 1 month ago"

update_user_stats:
  cron: "0 0 * * 6"
  class: "Scheduler::TotalUserStatsJob"
  queue: default
  description: "Update user stats"

online_users_cleanup:
  cron: "0 2 * * 6"
  class: "Scheduler::OnlineUserStatsJob"
  queue: default
  description: "Update online users stats"  
